### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by bugadani**

### CODE REVIEW

**Review by lulf — APPROVED** [review]

**Review by newAM — APPROVED** [review]
Thanks!  bors r+

**Comment by bugadani** [comment]
I haven't seen anything bors-related around here, should that command work? 😄

**Comment by newAM** [comment]
Whoops, you're right, wrong repo for that!

**Comment by bugadani** [comment]
By the way, I didn't notice this yesterday, but wasn't this comment incorrect in the first place? Sure, the buffer should be large enough to contain expected data (duh), but the function copies out partial records just fine.

**Pull request merged**
