### PR TITLE
Allow breaking up KeySchedule into read/write parts.

### PR DESCRIPTION
**Pull request by bugadani**

### CODE REVIEW

**Comment by bugadani** [comment]
This is a bit of a usability regression, to be fair, but I really don't want to complicate things by introducing a bunch of traits and I don't have any better idea.

**Comment by lulf** [comment]
The change itself looks good, but I'm trying to understand the path forward. Is your intent to introduce a TlsConnection.split() that can be called after the handshake is complete?

**Review by lulf — APPROVED** [review]
I like small PRs too, just wanted to make sure

**Comment by bugadani** [comment]
I'll keep the PR as a draft for now. It's reasonably complex that I want to test it better and to see if this is good enough to build the rest of the feature upon. I'll get back to this once I'm ready with the follow-up. :)

**Comment by lulf** [comment]
I think it might be needed on cipher change, but would need to read up on the RFC again

**Review by lulf — APPROVED** [review]

**Pull request merged**
