### PR TITLE
Allow splitting a connection into read/write parts

### PR DESCRIPTION
**Pull request by bugadani**
There are two ways to split a connection:
 - using `std`, calling `.split()` will create a heap-allocated shared state object
 - calling `.split_with(state)` where users can pass a reference to a `SplitConnectionState` instance

### CODE REVIEW

**Review by lulf — COMMENTED** [review]
I think the only thing preventing this to work on no-std is the Arc, so if you replace that with a &'a AtomicBool that you pass to split() that would at least get rid of std I think, even if the API is a bit clunky.

**Comment by lulf** [comment]
Yup, some trait could work, or maybe an enum. The atomic_polyfill crate is a drop-in for core::sync::atomic that you can use. I think the split reader/writer is not that uncommon, in fact you can do this with embassy-net/smoltcp, so it would be a useful feature in no_std as well.

**Comment by bugadani** [comment]
At this point all I can say is that this thing compiles for me using the owned state. I need to come up with test cases and most likely specify some lifetimes, but this whole journey turned out to be much less complicated than I expected.

**Comment by bugadani** [comment]
Blocked on https://github.com/embassy-rs/embedded-io/pull/14 as I'm lazy to write 5 lines of code for tests :)

**Comment by bugadani** [comment]
> I think the only thing preventing this to work on no-std is the Arc, so if you replace that with a &'a AtomicBool that you pass to split() that would at least get rid of std I think, even if the API is a bit clunky.

Actually, this is pretty unsound. Users would technically be allowed to split multiple connections using the same state, which doesn't sound like something we should allow.

**Review by lulf — APPROVED** [review]
🚀

**Pull request merged**
